[package]
name = "torrent"
version = "0.1.0"
edition = "2021"

[dependencies]
qbit-rs = { workspace = true }
dotenv = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
